openapi: '3.0.2'
info:
  title: Image API
  version: '1.0'
servers:
  - url: https://api-dev.apigee-x.theapishop.com/ai
security:
  - ApiKeyAuth: [] 
paths:
  /image:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                requests:
                  type: array
                  items:
                    type: object
                    properties:
                      image:
                        type: object
                        properties:
                          source:
                            type: object
                            properties:
                              imageUri:
                                type: string
                                description: The URI to find the image at
                                example: 'https://bit.ly/3klMXsX'
                      features:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                              description: 'The type of image detection'
                              example: 'TEXT_DETECTION'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  responses:
                    type: array
                    items:
                      type: object
                      properties:
                        textAnnotations:
                          type: array
                          items:
                            type: object
                            properties:
                              locale:
                                type: string
                                description: 'The langauge code of the text'
                                example: 'en'
                              description:
                                type: string
                                description: 'The extracted text block'
                                example: 'Fuel your ambitions'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: x-apikey
      in: header